from homeassistant.const import Platform

DOMAIN = "google_calendar_push"
CONF_CALENDARS = "configured_calendars"
CONF_CALENDAR_ALIASES = "calendar_aliases"

# Signal used to communicate between the REST API and the Sensors
SIGNAL_UPDATE_ENDPOINT = f"{DOMAIN}_update_endpoint"

# Tell HA to load our sensor file
PLATFORMS = [Platform.SENSOR]

OAUTH2_SCOPES = [
    "https://www.googleapis.com/auth/calendar.readonly",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/userinfo.email"
]

# Wire Contract Schema Version
SCHEMA_VERSION = 1

# Item-level Acknowledgement Semantics
STATUS_ACCEPTED = "accepted"
STATUS_APPLIED = "applied"
STATUS_ALREADY_APPLIED = "already_applied"
STATUS_STALE_IGNORED = "stale_ignored"
STATUS_REJECTED = "rejected"
STATUS_RETRYABLE = "retryable"
STATUS_CONFLICT = "conflict"

# Envelope Overall Status
OVERALL_SUCCESS = "success"
OVERALL_PARTIAL = "partial"
OVERALL_ERROR = "error"

# Canonical Operations
OPERATION_UPSERT = "upsert"
OPERATION_REMOVE = "remove"

# Machine-Readable Error Codes
CODE_AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
CODE_AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
CODE_INVALID_REQUEST = "INVALID_REQUEST"
CODE_INVALID_EVENT = "INVALID_EVENT"
CODE_UNSUPPORTED_RECURRENCE = "UNSUPPORTED_RECURRENCE"
CODE_STALE_REVISION = "STALE_REVISION"
CODE_IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
CODE_TARGET_UNAVAILABLE = "TARGET_UNAVAILABLE"
CODE_DOWNSTREAM_TIMEOUT = "DOWNSTREAM_TIMEOUT"
CODE_RATE_LIMITED = "RATE_LIMITED"
CODE_INTERNAL_ERROR = "INTERNAL_ERROR"

# Snapshot Reconciliation Error Codes
CODE_SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
CODE_SNAPSHOT_INCOMPLETE = "SNAPSHOT_INCOMPLETE"
CODE_SNAPSHOT_DIGEST_MISMATCH = "SNAPSHOT_DIGEST_MISMATCH"
CODE_SNAPSHOT_SEQUENCE_INVALID = "SNAPSHOT_SEQUENCE_INVALID"
CODE_SNAPSHOT_SUPERSEDED = "SNAPSHOT_SUPERSEDED"
CODE_SNAPSHOT_FINALIZE_CONFLICT = "SNAPSHOT_FINALIZE_CONFLICT"

# Snapshot Modes, Phases & Lifecycle Statuses
SNAPSHOT_MODE_REPLACE_ALL = "replace_all"

SNAPSHOT_PHASE_BEGIN = "begin"
SNAPSHOT_PHASE_ITEMS = "items"
SNAPSHOT_PHASE_FINALIZE = "finalize"

SNAPSHOT_STATUS_OPEN = "open"
SNAPSHOT_STATUS_RECEIVING = "receiving"
SNAPSHOT_STATUS_COMPLETED = "completed"
SNAPSHOT_STATUS_SUPERSEDED = "superseded"
SNAPSHOT_STATUS_FAILED = "failed"

# HTTP Headers
HEADER_IDEMPOTENCY_KEY = "Idempotency-Key"
HEADER_REQUEST_ID = "X-Request-ID"
HEADER_RETRY_AFTER = "Retry-After"

# Storage Configuration
STORAGE_VERSION = 1
STORAGE_KEY_PREFIX = f"{DOMAIN}_store"
DEFAULT_IDEMPOTENCY_TTL_DAYS = 7
DEFAULT_TOMBSTONE_RETENTION_DAYS = 30
DEFAULT_SNAPSHOT_TTL_DAYS = 7